from queue import Queue

QUOTE_ORDER_MIN = 10
PUBLIC_SLEEP = 0.4
PRIVATE_SLEEP = 0.21
MIN_PORTFOLIO_VALUE = 50 # This is the value that will trigger the bot to stop trading
TRADE_LEN = 120 # This is the amount of time I desire for trades to be filled in
OPEN_ORDERS = None
PRIVATE_SLEEP_QUEUE = Queue()
PRIVATE_SLEEP_QUEUE.put(0)
PUBLIC_SLEEP_QUEUE = Queue()
PUBLIC_SLEEP_QUEUE.put(0)

EXCHANGE_CONSTANTS = {
 'LINK-USD':{'base order min': 1.0, 'base resolution': 2, 'resolution': 5, 'avoid': False},
 'LINK':{'base order min': 1.0, 'base resolution': 2, 'resolution': 5, 'avoid': False},
 'XRP-EUR':{'base order min': 1.0, 'base resolution': 0, 'resolution': 4, 'avoid': False},
 'ETC-BTC':{'base order min': 0.1, 'base resolution': 8, 'resolution': 6, 'avoid': False},
 'XLM-EUR':{'base order min': 1.0, 'base resolution': 0, 'resolution': 6, 'avoid': False},
 'ETH-DAI':{'base order min': 0.01, 'base resolution': 4, 'resolution': 2, 'avoid': True},
 'EOS-EUR':{'base order min': 0.1, 'base resolution': 1, 'resolution': 3, 'avoid': True},
 'REP-USD':{'base order min': 0.1, 'base resolution': 6, 'resolution': 2, 'avoid': False},
 'REP':{'base order min': 0.1, 'base resolution': 6, 'resolution': 2, 'avoid': False},
 'MKR-BTC':{'base order min': 0.001, 'base resolution': 6, 'resolution': 5, 'avoid': False},
 'ETC-EUR':{'base order min': 0.1, 'base resolution': 8, 'resolution': 3, 'avoid': False},
 'XRP-BTC':{'base order min': 1.0, 'base resolution': 0, 'resolution': 8, 'avoid': False},
 'BTC-USDC':{'base order min': 0.001, 'base resolution': 8, 'resolution': 2, 'avoid': False},
 'LINK-ETH':{'base order min': 1.0, 'base resolution': 2, 'resolution': 8, 'avoid': False},
 'XTZ-USD':{'base order min': 1.0, 'base resolution': 2, 'resolution': 4, 'avoid': False},
 'XTZ':{'base order min': 1.0, 'base resolution': 2, 'resolution': 4, 'avoid': False},
 'ATOM-USD':{'base order min': 0.1, 'base resolution': 1, 'resolution': 3, 'avoid': False},
 'ATOM':{'base order min': 0.1, 'base resolution': 1, 'resolution': 3, 'avoid': False},
 'LOOM-USDC':{'base order min': 1.0, 'base resolution': 0, 'resolution': 6, 'avoid': True},
 'DAI-USD':{'base order min': 1.0, 'base resolution': 5, 'resolution': 6, 'avoid': True},
 'DAI':{'base order min': 1.0, 'base resolution': 5, 'resolution': 6, 'avoid': True},
 'DNT-USDC':{'base order min': 1.0, 'base resolution': 0, 'resolution': 6, 'avoid': True},
 'KNC-BTC':{'base order min': 1.0, 'base resolution': 1, 'resolution': 8, 'avoid': False},
 'EOS-BTC':{'base order min': 0.1, 'base resolution': 1, 'resolution': 6, 'avoid': True},
 'CVC-USDC':{'base order min': 1.0, 'base resolution': 0, 'resolution': 6, 'avoid': True},
 'LTC-USD':{'base order min': 0.1, 'base resolution': 8, 'resolution': 2, 'avoid': False},
 'LTC':{'base order min': 0.1, 'base resolution': 8, 'resolution': 2, 'avoid': False},
 'MANA-USDC':{'base order min': 1.0, 'base resolution': 0, 'resolution': 6, 'avoid': True},
 'XTZ-BTC':{'base order min': 1.0, 'base resolution': 2, 'resolution': 8, 'avoid': False},
 'LTC-GBP':{'base order min': 0.1, 'base resolution': 8, 'resolution': 2, 'avoid': False},
 'OMG-GBP':{'base order min': 1.0, 'base resolution': 1, 'resolution': 4, 'avoid': False},
 'ZRX-EUR':{'base order min': 1.0, 'base resolution': 5, 'resolution': 6, 'avoid': False},
 'DASH-BTC':{'base order min': 0.01, 'base resolution': 3, 'resolution': 8, 'avoid': False},
 'OXT-USD':{'base order min': 1.0, 'base resolution': 0, 'resolution': 4, 'avoid': False},
 'OXT':{'base order min': 1.0, 'base resolution': 0, 'resolution': 4, 'avoid': False},
 'BCH-GBP':{'base order min': 0.01, 'base resolution': 8, 'resolution': 2, 'avoid': False},
 'BAT-ETH':{'base order min': 1.0, 'base resolution': 0, 'resolution': 8, 'avoid': True},
 'ETH-GBP':{'base order min': 0.01, 'base resolution': 8, 'resolution': 2, 'avoid': False},
 'GNT-USDC':{'base order min': 1.0, 'base resolution': 0, 'resolution': 6, 'avoid': True},
 'BTC-GBP':{'base order min': 0.001, 'base resolution': 8, 'resolution': 2, 'avoid': False},
 'ETH-USD':{'base order min': 0.01, 'base resolution': 8, 'resolution': 2, 'avoid': False},
 'ETH':{'base order min': 0.01, 'base resolution': 8, 'resolution': 2, 'avoid': False},
 'EOS-USD':{'base order min': 0.1, 'base resolution': 1, 'resolution': 3, 'avoid': False},
 'EOS':{'base order min': 0.1, 'base resolution': 1, 'resolution': 3, 'avoid': False},
 'OMG-EUR':{'base order min': 1.0, 'base resolution': 1, 'resolution': 4, 'avoid': False},
 'OMG-USD':{'base order min': 1.0, 'base resolution': 1, 'resolution': 4, 'avoid': False},
 'OMG':{'base order min': 1.0, 'base resolution': 1, 'resolution': 4, 'avoid': False},
 'ATOM-BTC':{'base order min': 0.1, 'base resolution': 1, 'resolution': 6, 'avoid': False},
 'BTC-EUR':{'base order min': 0.001, 'base resolution': 8, 'resolution': 2, 'avoid': False},
 'BAT-USDC':{'base order min': 1.0, 'base resolution': 0, 'resolution': 6, 'avoid': False},
 'ZRX-BTC':{'base order min': 1.0, 'base resolution': 5, 'resolution': 8, 'avoid': False},
 'BCH-BTC':{'base order min': 0.01, 'base resolution': 8, 'resolution': 5, 'avoid': False},
 'XLM-BTC':{'base order min': 1.0, 'base resolution': 0, 'resolution': 8, 'avoid': False},
 'DASH-USD':{'base order min': 0.01, 'base resolution': 3, 'resolution': 3, 'avoid': False},
 'DASH':{'base order min': 0.01, 'base resolution': 3, 'resolution': 3, 'avoid': False},
 'ZEC-USDC':{'base order min': 0.01, 'base resolution': 8, 'resolution': 2, 'avoid': False},
 'ZEC-BTC':{'base order min': 0.01, 'base resolution': 4, 'resolution': 6, 'avoid': True},
 'XLM-USD':{'base order min': 1.0, 'base resolution': 0, 'resolution': 6, 'avoid': False},
 'XLM':{'base order min': 1.0, 'base resolution': 0, 'resolution': 6, 'avoid': False},
 'MKR-USD':{'base order min': 0.001, 'base resolution': 6, 'resolution': 4, 'avoid': False},
 'MKR':{'base order min': 0.001, 'base resolution': 6, 'resolution': 4, 'avoid': False},
 'ETH-USDC':{'base order min': 0.01, 'base resolution': 8, 'resolution': 2, 'avoid': False},
 'ETH-BTC':{'base order min': 0.01, 'base resolution': 8, 'resolution': 5, 'avoid': False},
 'ZRX-USD':{'base order min': 1.0, 'base resolution': 5, 'resolution': 6, 'avoid': False},
 'ZRX':{'base order min': 1.0, 'base resolution': 5, 'resolution': 6, 'avoid': False},
 'ETC-USD':{'base order min': 0.1, 'base resolution': 8, 'resolution': 3, 'avoid': False},
 'ETC':{'base order min': 0.1, 'base resolution': 8, 'resolution': 3, 'avoid': False},
 'DAI-USDC':{'base order min': 1.0, 'base resolution': 5, 'resolution': 6, 'avoid': True},
 'REP-BTC':{'base order min': 0.1, 'base resolution': 6, 'resolution': 6, 'avoid': True},
 'KNC-USD':{'base order min': 1.0, 'base resolution': 1, 'resolution': 4, 'avoid': False},
 'KNC':{'base order min': 1.0, 'base resolution': 1, 'resolution': 4, 'avoid': False},
 'ETC-GBP':{'base order min': 0.1, 'base resolution': 8, 'resolution': 3, 'avoid': False},
 'ETH-EUR':{'base order min': 0.01, 'base resolution': 8, 'resolution': 2, 'avoid': False},
 'OMG-BTC':{'base order min': 1.0, 'base resolution': 1, 'resolution': 8, 'avoid': False},
 'BCH-USD':{'base order min': 0.01, 'base resolution': 8, 'resolution': 2, 'avoid': False},
 'BCH':{'base order min': 0.01, 'base resolution': 8, 'resolution': 2, 'avoid': False},
 'LTC-BTC':{'base order min': 0.1, 'base resolution': 8, 'resolution': 6, 'avoid': False},
 'LTC-EUR':{'base order min': 0.1, 'base resolution': 8, 'resolution': 2, 'avoid': False},
 'XRP-USD':{'base order min': 1.0, 'base resolution': 0, 'resolution': 4, 'avoid': False},
 'XRP':{'base order min': 1.0, 'base resolution': 0, 'resolution': 4, 'avoid': False},
 'BCH-EUR':{'base order min': 0.01, 'base resolution': 8, 'resolution': 2, 'avoid': False},
 'ALGO-USD':{'base order min': 1.0, 'base resolution': 0, 'resolution': 4, 'avoid': False},
 'ALGO':{'base order min': 1.0, 'base resolution': 0, 'resolution': 4, 'avoid': False},
 'BTC-USD':{'base order min': 0.001, 'base resolution': 8, 'resolution': 2, 'avoid': False},
 'BTC':{'base order min': 0.001, 'base resolution': 8, 'resolution': 2, 'avoid': False},
}
