# EXCHANGE_CONSTANTS = {'BTC':{'resolution':2, 'base order min':0.001, 'base resolution':8},
#                       'ETH':{'resolution':2, 'base order min':0.01, 'base resolution':8},
#                       'XRP':{'resolution':4, 'base order min':1, 'base resolution':0},
#                       'LTC':{'resolution':2, 'base order min':0.1, 'base resolution':8},
#                       'BCH':{'resolution':2, 'base order min':0.01, 'base resolution':8},
#                       'EOS':{'resolution':3, 'base order min':0.1, 'base resolution':1},
#                       'XLM':{'resolution':6, 'base order min':1, 'base resolution':0},
#                       'ETC':{'resolution':3, 'base order min':0.1, 'base resolution':8},
#                       'LINK':{'resolution':5, 'base order min':1, 'base resolution':1},
#                       'REP':{'resolution':2, 'base order min':0.1, 'base resolution':6},
#                       'ZRX':{'resolution':6, 'base order min':1, 'base resolution':5},
#                       'XTZ':{'resolution':3, 'base order min':1, 'base resolution':1},
#                       'ALGO':{'resolution':4, 'base order min':1, 'base resolution':0}
#                       }

EXCHANGE_CONSTANTS = {
    'BCH-GBP':{'base order min': 0.01, 'base resolution': 8, 'resolution': 2, 'avoid': False},
    'EOS-USD':{'base order min': 0.1, 'base resolution': 1, 'resolution': 3, 'avoid': False},
    'EOS':{'base order min': 0.1, 'base resolution': 1, 'resolution': 3, 'avoid': False},
    'REP-USD':{'base order min': 0.1, 'base resolution': 6, 'resolution': 2, 'avoid': False},
    'REP':{'base order min': 0.1, 'base resolution': 6, 'resolution': 2, 'avoid': False},
    'ETH-EUR':{'base order min': 0.01, 'base resolution': 8, 'resolution': 2, 'avoid': False},
    'LTC-USD':{'base order min': 0.1, 'base resolution': 8, 'resolution': 2, 'avoid': False},
    'LTC':{'base order min': 0.1, 'base resolution': 8, 'resolution': 2, 'avoid': False},
    'BAT-USDC':{'base order min': 1.0, 'base resolution': 0, 'resolution': 6, 'avoid': False},
    'XTZ-BTC':{'base order min': 1.0, 'base resolution': 2, 'resolution': 8, 'avoid': False},
    'BAT-ETH':{'base order min': 1.0, 'base resolution': 0, 'resolution': 8, 'avoid': True},
    'ETH-DAI':{'base order min': 0.01, 'base resolution': 4, 'resolution': 2, 'avoid': True},
    'EOS-EUR':{'base order min': 0.1, 'base resolution': 1, 'resolution': 3, 'avoid': True},
    'XLM-EUR':{'base order min': 1.0, 'base resolution': 0, 'resolution': 6, 'avoid': False},
    'EOS-BTC':{'base order min': 0.1, 'base resolution': 1, 'resolution': 6, 'avoid': True},
    'BTC-USD':{'base order min': 0.001, 'base resolution': 8, 'resolution': 2, 'avoid': False},
    'BTC':{'base order min': 0.001, 'base resolution': 8, 'resolution': 2, 'avoid': False},
    'LTC-BTC':{'base order min': 0.1, 'base resolution': 8, 'resolution': 6, 'avoid': False},
    'BCH-BTC':{'base order min': 0.01, 'base resolution': 8, 'resolution': 5, 'avoid': False},
    'GNT-USDC':{'base order min': 1.0, 'base resolution': 0, 'resolution': 6, 'avoid': True},
    'REP-BTC':{'base order min': 0.1, 'base resolution': 6, 'resolution': 6, 'avoid': True},
    'XLM-BTC':{'base order min': 1.0, 'base resolution': 0, 'resolution': 8, 'avoid': False},
    'LINK-ETH':{'base order min': 1.0, 'base resolution': 2, 'resolution': 8, 'avoid': False},
    'LTC-EUR':{'base order min': 0.1, 'base resolution': 8, 'resolution': 2, 'avoid': False},
    'ZEC-BTC':{'base order min': 0.01, 'base resolution': 4, 'resolution': 6, 'avoid': True},
    'ZRX-BTC':{'base order min': 1.0, 'base resolution': 5, 'resolution': 8, 'avoid': False},
    'DNT-USDC':{'base order min': 1.0, 'base resolution': 0, 'resolution': 6, 'avoid': True},
    'ETC-GBP':{'base order min': 0.1, 'base resolution': 8, 'resolution': 3, 'avoid': False},
    'BTC-EUR':{'base order min': 0.001, 'base resolution': 8, 'resolution': 2, 'avoid': False},
    'DAI-USDC':{'base order min': 1.0, 'base resolution': 5, 'resolution': 6, 'avoid': True},
    'LINK-USD':{'base order min': 1.0, 'base resolution': 2, 'resolution': 5, 'avoid': False},
    'LINK':{'base order min': 1.0, 'base resolution': 2, 'resolution': 5, 'avoid': False},
    'ETC-EUR':{'base order min': 0.1, 'base resolution': 8, 'resolution': 3, 'avoid': False},
    'CVC-USDC':{'base order min': 1.0, 'base resolution': 0, 'resolution': 6, 'avoid': True},
    'XRP-USD':{'base order min': 1.0, 'base resolution': 0, 'resolution': 4, 'avoid': False},
    'XRP':{'base order min': 1.0, 'base resolution': 0, 'resolution': 4, 'avoid': False},
    'LOOM-USDC':{'base order min': 1.0, 'base resolution': 0, 'resolution': 6, 'avoid': True},
    'ETH-BTC':{'base order min': 0.01, 'base resolution': 8, 'resolution': 5, 'avoid': False},
    'XTZ-USD':{'base order min': 1.0, 'base resolution': 2, 'resolution': 4, 'avoid': False},
    'XTZ':{'base order min': 1.0, 'base resolution': 2, 'resolution': 4, 'avoid': False},
    'BCH-USD':{'base order min': 0.01, 'base resolution': 8, 'resolution': 2, 'avoid': False},
    'BCH':{'base order min': 0.01, 'base resolution': 8, 'resolution': 2, 'avoid': False},
    'MANA-USDC':{'base order min': 1.0, 'base resolution': 0, 'resolution': 6, 'avoid': True},
    'ETH-USDC':{'base order min': 0.01, 'base resolution': 8, 'resolution': 2, 'avoid': False},
    'XLM-USD':{'base order min': 1.0, 'base resolution': 0, 'resolution': 6, 'avoid': False},
    'XLM':{'base order min': 1.0, 'base resolution': 0, 'resolution': 6, 'avoid': False},
    'XRP-BTC':{'base order min': 1.0, 'base resolution': 0, 'resolution': 8, 'avoid': False},
    'BTC-GBP':{'base order min': 0.001, 'base resolution': 8, 'resolution': 2, 'avoid': False},
    'XRP-EUR':{'base order min': 1.0, 'base resolution': 0, 'resolution': 4, 'avoid': False},
    'ETC-USD':{'base order min': 0.1, 'base resolution': 8, 'resolution': 3, 'avoid': False},
    'ETC':{'base order min': 0.1, 'base resolution': 8, 'resolution': 3, 'avoid': False},
    'LTC-GBP':{'base order min': 0.1, 'base resolution': 8, 'resolution': 2, 'avoid': False},
    'ETH-USD':{'base order min': 0.01, 'base resolution': 8, 'resolution': 2, 'avoid': False},
    'ETH':{'base order min': 0.01, 'base resolution': 8, 'resolution': 2, 'avoid': False},
    'BTC-USDC':{'base order min': 0.001, 'base resolution': 8, 'resolution': 2, 'avoid': False},
    'ZEC-USDC':{'base order min': 0.01, 'base resolution': 8, 'resolution': 2, 'avoid': False},
    'ALGO-USD':{'base order min': 1.0, 'base resolution': 0, 'resolution': 4, 'avoid': False},
    'ALGO':{'base order min': 1.0, 'base resolution': 0, 'resolution': 4, 'avoid': False},
    'ETC-BTC':{'base order min': 0.1, 'base resolution': 8, 'resolution': 6, 'avoid': False},
    'ETH-GBP':{'base order min': 0.01, 'base resolution': 8, 'resolution': 2, 'avoid': False},
    'ZRX-USD':{'base order min': 1.0, 'base resolution': 5, 'resolution': 6, 'avoid': False},
    'ZRX':{'base order min': 1.0, 'base resolution': 5, 'resolution': 6, 'avoid': False},
    'BCH-EUR':{'base order min': 0.01, 'base resolution': 8, 'resolution': 2, 'avoid': False},
    'ZRX-EUR':{'base order min': 1.0, 'base resolution': 5, 'resolution': 6, 'avoid': False},
}